application: eqjpviz
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /worker/.*
  script: workers.py

- url: /.*
  script: handlers.py